version: '3.8'

services:
  frontend:
    build:
      context: ./inventory-management-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - event-processor

  event-processor:
    build:
      context: ./event-processor-container
      dockerfile: Dockerfile
    volumes:
      - ./event-processor-container:/app
