apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: inventory-system
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007  # Kubernetes will expose this port
  type: NodePort

